/**
 * Pure helpers + types for brand asset visual analysis. Kept separate from
 * `assetAnalysis.ts` (which pulls in the Gemini SDK) so widely-imported callers
 * like `brandContextBuilder` can aggregate signatures without the LLM dependency.
 */

export interface BrandAssetDimensions {
  vibe?: string[]; // emotional tone: premium, playful, bold, calm, edgy, corporate…
  aesthetic?: string[]; // visual style: minimalist, brutalist, editorial, retro, organic…
  theme?: string[]; // subject/motif: abstract, geometric, nature, urban, human, typographic…
  mood?: string[]; // color/light mood: warm, cool, vibrant, muted, pastel, monochrome…
  medium?: string[]; // treatment: photography, 3d, illustration, vector, flat, gradient, grain…
}

/** What KIND of asset this is — drives which scene surface it belongs on. */
export type BrandAssetKind =
  | 'logo' // full lockup (symbol + wordmark)
  | 'wordmark' // text-only logotype
  | 'symbol' // icon/mark only
  | 'photo' // photograph
  | 'pattern' // repeating motif
  | 'texture' // surface/material
  | 'graphic' // designed composition / campaign art
  | 'illustration';

/**
 * Placement metadata — the mechanical facts needed to composite an asset onto a
 * mockup surface WITHOUT it looking wrong. Distinct from the aesthetic
 * `dimensions` (which feed AI prompts): placement feeds the deterministic
 * scene matcher (`packages/psd-engine` renderScene). Semantic fields come from
 * the vision model; measured fields (aspectRatio/hasTransparency/dominantColor)
 * are computed deterministically via sharp; textBox/safeCrop vêm de OCR.
 *
 * A divisão não é estilística — é o que os dados mostraram: o modelo de visão
 * acerta o QUE a peça é e erra ONDE as coisas estão (ver textBox).
 */
export interface BrandAssetPlacement {
  kind?: BrandAssetKind; // LLM — what the asset is
  luminance?: 'light' | 'dark' | 'mixed'; // LLM — overall light/dark of the art
  hasText?: boolean; // LLM — is there legible text
  text?: string; // LLM — the actual text, verbatim, if any
  contrastSafeOn?: ('light' | 'dark')[]; // LLM — backgrounds it stays legible on
  aspectRatio?: number; // sharp — width / height
  hasTransparency?: boolean; // sharp — has real alpha (can be "pasted", no frame)
  dominantColor?: string; // sharp — dominant hex, for contrast checks

  /**
   * Caixa (normalizada 0..1) que engloba todo texto/logo. É o "onde" que o
   * `hasText` não responde. Ausente = não medido ou leitura descartada.
   *
   * Vem do Gemini via `box_2d` (convenção nativa dele: [ymin,xmin,ymax,xmax] em
   * 0-1000). Isso NÃO vale pra qualquer modelo de visão: medimos claude-haiku
   * devolvendo caixas quantizadas (0.10/0.90 repetidas) com confidence 0.95 —
   * prior, não medição. Num bake-off de 30 artes, Gemini respondeu 30/30 com
   * erro de 0.9pp contra gabarito medido; tesseract 15/30 com 0.4pp.
   */
  textBox?: { x0: number; y0: number; x1: number; y1: number };
  /**
   * Fração TOTAL da arte que o `cover` pode descartar sem tocar no texto.
   * O corte é centrado, então cada lado perde metade → 2× a menor margem.
   * Ausente = desconhecido; o caller deve assumir o conservador (não cortar).
   */
  safeCrop?: number;
  /** Proveniência — `geometry` é fallback e costuma subestimar. */
  safeCropSource?: 'vision' | 'ocr' | 'geometry';
}

export interface BrandAssetAnalysis {
  /**
   * Short human-readable name for the asset, 2-4 words, in English and
   * Portuguese. Produced by the same vision call that fills `dimensions`, so it
   * costs nothing extra.
   *
   * Exists because assets arriving from Figma carry the LAYER NAME as their
   * label — "Frame 4836", "Group 12" — and the media kit is INPUT for
   * generation, so that noise reaches the prompt. See `isAutoGeneratedLabel`.
   */
  name?: string;
  namePt?: string;
  description?: string;
  dimensions?: BrandAssetDimensions;
  placement?: BrandAssetPlacement;
  analyzedAt?: string;
  model?: string;
}

export interface BrandVisualSignature {
  vibe: string[];
  aesthetic: string[];
  theme: string[];
  mood: string[];
  medium: string[];
}

export const SIGNATURE_KEYS: (keyof BrandAssetDimensions)[] = [
  'vibe',
  'aesthetic',
  'theme',
  'mood',
  'medium',
];

/**
 * Aggregate per-asset dimensions into a brand-level visual signature: the most
 * frequent tags across all analyzed assets (top 5 per dimension). This is the
 * compact, derived datum the API exposes for generation context.
 */
export function aggregateVisualSignature(
  assets: Array<{ analysis?: BrandAssetAnalysis | null }>
): BrandVisualSignature {
  const counts: Record<string, Map<string, number>> = {};
  for (const key of SIGNATURE_KEYS) counts[key] = new Map();

  for (const a of assets) {
    const dims = a?.analysis?.dimensions;
    if (!dims) continue;
    for (const key of SIGNATURE_KEYS) {
      for (const raw of dims[key] || []) {
        const tag = String(raw).trim().toLowerCase();
        if (!tag) continue;
        counts[key].set(tag, (counts[key].get(tag) || 0) + 1);
      }
    }
  }

  const top = (key: string) =>
    [...counts[key].entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([tag]) => tag);

  return {
    vibe: top('vibe'),
    aesthetic: top('aesthetic'),
    theme: top('theme'),
    mood: top('mood'),
    medium: top('medium'),
  };
}

/** True when a signature has at least one tag (worth exposing). */
export function hasSignature(sig: BrandVisualSignature | undefined | null): boolean {
  return (
    !!sig &&
    SIGNATURE_KEYS.some((k) => Array.isArray((sig as any)[k]) && (sig as any)[k].length > 0)
  );
}
