import { describe, it, expect } from 'vitest';
import {
  calculateCompleteness,
  assessCompleteness,
  recomputeExtraction,
} from '../../types/brandGuideline.js';
import { computeBrandCompleteness } from '../../../src/lib/brandCompleteness.js';
import { isAutoGeneratedLabel, cleanName } from '../brand/assetAnalysis.js';

// The server used to score completeness with 14 independent checkboxes worth
// 7.14 points each, while the UI pill scored the same brand with 18 weighted
// rules. Two numbers for one brand: the pill said one thing, the API and MCP
// said another. These lock the single scorer in place.

const sparse = {
  identity: { name: 'Arbolt' },
  colors: [{ hex: '#2C352F', name: 'Musgo', role: 'primary' }],
} as any;

const withStrategy = {
  ...sparse,
  strategy: {
    manifesto: 'Plantar é infraestrutura.',
    personas: [{ name: 'Ana' }, { name: 'Bruno' }, { name: 'Carla' }],
    archetypes: [{ name: 'Caretaker' }],
    marketResearch: { competitors: new Array(12).fill({ name: 'x' }) },
    graphicSystem: { patterns: ['grid'] },
  },
  guidelines: { voice: 'Direta e técnica.', dos: ['ser claro'], donts: ['adjetivo vazio'] },
} as any;

describe('completeness — one scorer for the whole product', () => {
  it('server score matches the scorer the UI pill renders', () => {
    for (const brand of [sparse, withStrategy]) {
      expect(calculateCompleteness(brand)).toBe(computeBrandCompleteness(brand).score);
    }
  });

  it('moves when real strategy work lands (the old checkbox scorer barely did)', () => {
    expect(calculateCompleteness(withStrategy)).toBeGreaterThan(calculateCompleteness(sparse));
  });

  it('counts a logo — the upload route used to leave the score frozen', () => {
    const before = calculateCompleteness(withStrategy);
    const after = calculateCompleteness({
      ...withStrategy,
      logos: [
        { id: '1', url: 'u', variant: 'primary' },
        { id: '2', url: 'u2', variant: 'dark' },
      ],
    } as any);
    expect(after).toBeGreaterThan(before);
  });

  it('reports what is missing, not just a number', () => {
    const report = assessCompleteness(sparse);
    expect(report.missing.length).toBeGreaterThan(0);
    expect(report.missing.map((r) => r.id)).toContain('typography');
    for (const rule of report.missing) {
      expect(rule.weight).toBeGreaterThan(0);
      expect(rule.label).toBeTruthy();
    }
  });
});

describe('recomputeExtraction — SSoT for restating completeness on write', () => {
  it('refreshes the score while preserving existing sources', () => {
    const sources = [{ type: 'url' as const, ref: 'https://arbolt.com', date: '2026-08-05' }];
    const out = recomputeExtraction({ ...withStrategy, extraction: { sources, completeness: 3 } });

    expect(out.sources).toEqual(sources);
    expect(out.completeness).toBe(calculateCompleteness(withStrategy));
    expect(out.completeness).not.toBe(3);
  });

  it('tolerates a guideline that never had extraction metadata', () => {
    const out = recomputeExtraction(sparse);
    expect(out.sources).toEqual([]);
    expect(typeof out.completeness).toBe('number');
  });
});

describe('isAutoGeneratedLabel — Figma layer names must not become asset labels', () => {
  it('flags machine debris', () => {
    for (const label of [
      'Frame 4836',
      'Group 12',
      'Rectangle',
      'Union',
      'Vector 3',
      'Component 1',
      'IMG_2043.png',
      'union.svg',
      '42',
      'a3f9c2e10b4d',
      '',
      '   ',
      undefined,
    ]) {
      expect(isAutoGeneratedLabel(label as any), `expected auto: ${label}`).toBe(true);
    }
  });

  it('leaves anything a person wrote alone', () => {
    for (const label of [
      'Logo horizontal',
      'Campanha Verão 2026',
      'Founder Portrait',
      'Padrão de folhas',
      'Frame do manifesto',
    ]) {
      expect(isAutoGeneratedLabel(label), `expected human: ${label}`).toBe(false);
    }
  });

  it('rejects a model that just echoes the layer name back', () => {
    expect(cleanName('Frame 4836')).toBeUndefined();
    expect(cleanName('Coral Gradient Backdrop')).toBe('Coral Gradient Backdrop');
    expect(cleanName('  Retrato\nda Fundadora ')).toBe('Retrato da Fundadora');
  });
});
