import React from 'react';
import { SlidersHorizontal } from 'lucide-react';
import { useMockup } from './MockupContext';
import { useTranslation } from '@/hooks/useTranslation';
import { useTheme } from '@/hooks/useTheme';
import { ModelSelector } from '@/components/shared/ModelSelector';
import { MockupConfigSummary } from './MockupConfigSummary';
import { ToggleRow } from './ToggleRow';
import {
  ToolPanelSection,
  ToolPanelGrid,
  ToolPanelChip,
  ToolPanelDivider,
  ToolPanelRow,
} from '@/components/shared/ToolPanel';
import { GEMINI_MODELS } from '@/constants/geminiModels';
import type { Resolution, AspectRatio } from '@/types/types';

const GEMINI_RESOLUTIONS: Resolution[] = ['HD', '1K', '2K', '4K'];
const SEEDREAM_RESOLUTIONS: Resolution[] = ['2K', '4K'];
const ASPECT_RATIOS: AspectRatio[] = ['1:1', '9:16', '16:9', '4:3', '3:4'];

export const MockupOutputConfig: React.FC = () => {
  const { t } = useTranslation();
  const { theme } = useTheme();
  const dark = theme === 'dark';

  const {
    selectedModel,
    setSelectedModel,
    resolution,
    setResolution,
    aspectRatio,
    setAspectRatio,
    imageProvider,
    setImageProvider,
    autoGenerate,
    setAutoGenerate,
    isSurpriseMeMode,
    setIsSurpriseMeMode,
  } = useMockup();

  const resolutions = imageProvider === 'seedream' ? SEEDREAM_RESOLUTIONS : GEMINI_RESOLUTIONS;

  const handleModelChange = (model: string, provider?: string) => {
    if (provider === 'seedream') {
      setImageProvider('seedream');
    } else {
      setImageProvider('gemini');
    }
    setSelectedModel(model as any);
  };

  return (
    <div className="space-y-4">
      {/* Header with status summary */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div className="w-6 h-6 rounded-md bg-neutral-900 border border-neutral-800/50 flex items-center justify-center">
            <SlidersHorizontal size={11} className="text-neutral-500" />
          </div>
          <span className="text-[10px] font-mono uppercase tracking-widest text-neutral-500">
            {t('mockup.aiSettings') || 'Output Config'}
          </span>
        </div>
        <MockupConfigSummary />
      </div>

      {/* Model Selector */}
      <ModelSelector
        type="image"
        selectedModel={
          selectedModel || (imageProvider === 'seedream' ? 'seedream-4.5' : GEMINI_MODELS.IMAGE_NB2)
        }
        onModelChange={handleModelChange}
        resolution={resolution}
        onSyncResolution={setResolution}
        className="w-full"
      />

      {/* Resolution + Aspect Ratio */}
      <div className="space-y-3">
        <ToolPanelSection title={t('mockup.resolutionLabel') || 'Resolução'}>
          <ToolPanelGrid cols={resolutions.length as 2 | 4}>
            {resolutions.map((res) => (
              <ToolPanelChip
                key={res}
                active={resolution === res}
                onClick={() => setResolution(res)}
              >
                {res}
              </ToolPanelChip>
            ))}
          </ToolPanelGrid>
        </ToolPanelSection>

        <ToolPanelSection title={t('mockup.aspectRatioLabel') || 'Proporção'}>
          <ToolPanelGrid cols={5}>
            {ASPECT_RATIOS.map((ratio) => (
              <ToolPanelChip
                key={ratio}
                active={aspectRatio === ratio}
                onClick={() => setAspectRatio(ratio)}
              >
                {ratio}
              </ToolPanelChip>
            ))}
          </ToolPanelGrid>
        </ToolPanelSection>
      </div>

      <ToolPanelDivider />

      {/* Toggles using ToolPanelRow for alignment */}
      <div className="space-y-2">
        <ToolPanelRow label={t('mockup.autoGenerateLabel') || 'Prompt + Imagem'}>
          <ToggleRow
            checked={autoGenerate}
            onClick={() => setAutoGenerate(!autoGenerate)}
            dark={dark}
            tooltip={
              t('mockup.autoGenerateDescription') ||
              'Gera prompt e imagem de uma vez. Desligado = só gera o prompt pra revisar.'
            }
          />
        </ToolPanelRow>
        <ToolPanelRow label={t('mockup.directorModeLabel') || 'Aleatorizar Tags'}>
          <ToggleRow
            checked={isSurpriseMeMode}
            onClick={() => setIsSurpriseMeMode(!isSurpriseMeMode)}
            dark={dark}
            tooltip={
              t('mockup.directorModeDescription') ||
              'Define quais categorias de tags serão sorteadas a cada geração'
            }
          />
        </ToolPanelRow>
      </div>
    </div>
  );
};
