/**
 * Documentation Routes
 * Serves API, MCP, and Plugin documentation with caching and error handling
 *
 * HTML templates live in server/docs/*.html — no inline HTML in this file.
 * JSON payloads are generated by lib/ generators — no hardcoded data here.
 */

import express, { Request, Response } from 'express';
import { readFileSync } from 'fs';
import { promises as fsAsync } from 'fs';
import { resolve, join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import { generateOpenAPISpec } from '../lib/openapi-gen.js';
import { generateMCPSpec, generatePlatformMCPSpec } from '../lib/mcp-gen.js';
import { getPricingPayload } from '../lib/pricing-data.js';
import { docsCache } from '../lib/docs-cache.js';
import {
  isDocumentationError,
  ValidationError,
} from '../lib/docs-errors.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const router = express.Router();

// ─── Constants ────────────────────────────────────────────────────────────────

const packageJson = JSON.parse(
  readFileSync(resolve(__dirname, '../../package.json'), 'utf-8')
);

const VERSION: string = packageJson.version || '1.0.0';
const SERVER_URL: string = process.env.SERVER_URL || 'http://localhost:3001';
const DOCS_DIR = resolve(__dirname, '../docs');

/** Baseline import count (Button component) used to normalise usage percentages */
const BUTTON_MAX_IMPORTS = 167;

// ─── Template loader ──────────────────────────────────────────────────────────

const templateCache = new Map<string, string>();

/**
 * Read an HTML template from server/docs/, replace {{VERSION}}, cache in memory.
 * Falls back to a minimal error page if the file is missing.
 */
function readTemplate(filename: string): string {
  if (templateCache.has(filename)) return templateCache.get(filename)!;

  let content: string;
  try {
    content = readFileSync(join(DOCS_DIR, filename), 'utf-8');
  } catch {
    content = `<html><body><h1>Template Not Found</h1><p>${filename} is missing from server/docs/</p></body></html>`;
  }

  const rendered = content.replace(/\{\{VERSION\}\}/g, VERSION);
  templateCache.set(filename, rendered);
  return rendered;
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

function setDocsHeaders(res: Response, ttl = 300): void {
  res.set('Cache-Control', `public, max-age=${ttl}`);
  res.set('X-Content-Type-Options', 'nosniff');
  res.set('X-Frame-Options', 'SAMEORIGIN');
}

function sendCachedJSON(res: Response, data: unknown, ttl = 300): void {
  setDocsHeaders(res, ttl);
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
  res.json(data);
}

function sendCachedHTML(res: Response, html: string, ttl = 3600): void {
  setDocsHeaders(res, ttl);
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.send(html);
}

function handleDocsError(err: unknown, res: Response): void {
  console.error('[Docs Error]:', err);

  if (isDocumentationError(err)) {
    setDocsHeaders(res);
    res.status(err.statusCode).json(err.toJSON());
  } else if (err instanceof Error) {
    setDocsHeaders(res);
    res.status(500).json({ error: err.message, code: 'INTERNAL_ERROR' });
  } else {
    setDocsHeaders(res);
    res.status(500).json({ error: 'Unknown error occurred', code: 'INTERNAL_ERROR' });
  }
}

function validateSearchQuery(query: string): string {
  if (!query || typeof query !== 'string') throw new ValidationError('Search query is required');

  const sanitized = query.trim();
  if (sanitized.length < 2) throw new ValidationError('Search query must be at least 2 characters', { length: sanitized.length });
  if (sanitized.length > 100) throw new ValidationError('Search query must not exceed 100 characters', { length: sanitized.length });
  if (/<[^>]*>|<script|<iframe|javascript:/i.test(sanitized)) throw new ValidationError('Invalid characters in search query');

  return sanitized;
}

/** Compute usage level and percentage for a component by its import count. */
function calcComponentUsage(imports: number): { percentage: number; level: string } {
  return {
    percentage: Math.min(100, (imports / BUTTON_MAX_IMPORTS) * 100),
    level: imports > 30 ? 'critical'
         : imports > 10 ? 'frequent'
         : imports > 2  ? 'moderate'
         : imports > 0  ? 'rare'
         : 'unused',
  };
}

// ─── Cache helpers ────────────────────────────────────────────────────────────

const TTL_SPEC   = 60 * 60 * 1000; // 1h — specs rarely change
const TTL_SEARCH = 10 * 60 * 1000; // 10m — search results

function getOpenAPISpec() {
  return docsCache.getOrGenerate('openapi-spec', () => generateOpenAPISpec(VERSION, SERVER_URL), TTL_SPEC);
}

function getMCPSpec() {
  return docsCache.getOrGenerate('mcp-spec', () => generateMCPSpec(), TTL_SPEC);
}

function getPlatformSpec() {
  return docsCache.getOrGenerate('platform-mcp-spec', () => generatePlatformMCPSpec(), TTL_SPEC);
}

// ─── Routes ───────────────────────────────────────────────────────────────────

router.get('/', (_req, res) => res.redirect('/docs'));
router.get('/api', (_req, res) => res.redirect('/docs'));
router.get('/plugin', (_req, res) => res.redirect('/docs'));
router.get('/plugin/mcp', (_req, res) => res.redirect('/docs'));

/**
 * GET /docs/api/spec
 * OpenAPI 3.0 Specification (JSON)
 */
router.get('/api/spec', (req: Request, res: Response) => {
  try {
    const spec = getOpenAPISpec();
    res.setHeader('X-API-Version', VERSION);
    sendCachedJSON(res, spec, 3600);
  } catch (err) {
    handleDocsError(err, res);
  }
});

/**
 * GET /docs/plugin/mcp.json
 * Figma MCP specification for LLMs / agents
 */
router.get('/plugin/mcp.json', (req: Request, res: Response) => {
  try {
    const spec = getMCPSpec();
    res.setHeader('X-MCP-Version', '1.0.0');
    sendCachedJSON(res, spec, 3600);
  } catch (err) {
    handleDocsError(err, res);
  }
});

/**
 * GET /docs/platform/mcp.json
 * Platform MCP spec — all tools for Claude.ai Connectors
 */
router.get('/platform/mcp.json', (req: Request, res: Response) => {
  try {
    const spec = getPlatformSpec();
    res.setHeader('X-MCP-Version', '2025-03-26');
    sendCachedJSON(res, spec, 3600);
  } catch (err) {
    handleDocsError(err, res);
  }
});

/**
 * GET /docs/pricing
 * Credit costs, packages, storage plans, Google pricing — single source of truth
 */
router.get('/pricing', (_req: Request, res: Response) => {
  try {
    const data = docsCache.getOrGenerate('pricing-data', getPricingPayload, TTL_SPEC);
    sendCachedJSON(res, data, 3600);
  } catch (err) {
    handleDocsError(err, res);
  }
});

/**
 * GET /docs/brand
 * Human-readable Brand Guidelines API reference (HTML)
 */
router.get('/brand', (_req: Request, res: Response) => {
  try {
    sendCachedHTML(res, readTemplate('brand-api.html'));
  } catch (err) {
    handleDocsError(err, res);
  }
});

/**
 * GET /docs/brand-prompting
 * Human-readable guide: how to write AI prompts using brand guidelines (HTML)
 */
router.get('/brand-prompting', (_req: Request, res: Response) => {
  try {
    sendCachedHTML(res, readTemplate('brand-prompting.html'));
  } catch (err) {
    handleDocsError(err, res);
  }
});

/**
 * GET /docs/brand-prompting.json
 * Machine-readable prompt writing guide for LLM agents
 */
router.get('/brand-prompting.json', (_req: Request, res: Response) => {
  sendCachedJSON(res, {
    title: 'Brand-Aware AI Prompting Guide',
    version: VERSION,
    coreRule: 'Pass brandGuidelineId and let the system inject brand assets automatically. Never describe logos or typography in prompt text.',
    autoInjectedWhenBrandGuidelineIdProvided: {
      logos: 'Up to 2 logo images passed as referenceImages (priority: primary → icon → light → dark)',
      mediaKit: 'Up to 2 style reference images from brand media[] passed as referenceImages',
      brandContext: 'Colors, typography, tone, dos/donts, imagery guidelines, strategy, positioning, archetypes, personas — prepended to prompt',
    },
    promptRules: {
      do: [
        'Describe composition, layout, mood, scene',
        'Reference brand name as a label ("brand logo at bottom")',
        'Use color names from brand palette',
        'Reference product category',
        'Describe photography style (motion blur, studio crisp, etc.)',
      ],
      dont: [
        'Describe logo visually (shape, colors, concentric circles icon, etc.)',
        'Reproduce typography by describing font weight/style',
        'Use generic colors that contradict the brand palette',
        'Ask for text overlays — image models render text poorly',
      ],
    },
    examples: {
      bad: 'Product post with SPORTS 248 logo featuring concentric circles bullseye icon in white Archivo Bold font at the bottom...',
      good: 'Product post. Dark navy background, cricket bats centered, brand logo at bottom.',
    },
    apiEndpoints: {
      generate: 'POST /api/mockups/generate',
      batchGenerate: 'POST /api/mockups/batch-generate',
      requiredField: 'brandGuidelineId',
    },
    models: [
      { id: 'gpt-image-1', provider: 'openai', strengths: 'Best brand fidelity with referenceImages', envVar: 'OPENAI_KEY or OPENAI_API_KEY' },
      { id: 'gpt-image-2', provider: 'openai', strengths: 'Higher quality, better text rendering', note: 'Requires OpenAI org verification' },
      { id: 'gemini-3.1-flash-image-preview', provider: 'gemini', strengths: 'Fast, stylized, creative compositions', envVar: 'GEMINI_API_KEY' },
      { id: 'seedream-3-0', provider: 'seedream', strengths: 'Photorealistic lifestyle photography', envVar: 'SEEDREAM_API_KEY' },
    ],
  }, 3600);
});

/**
 * GET /docs/api/api-keys
 * API Keys documentation
 */
router.get('/api/api-keys', (_req: Request, res: Response) => {
  sendCachedJSON(res, {
    title: 'API Keys',
    description: 'Manage API keys for programmatic access and MCP integrations.',
    endpoint: '/api/api-keys',
    authentication: 'JWT required (user session)',
    operations: [
      {
        method: 'POST',
        path: '/api/api-keys/create',
        description: 'Create a new API key. Raw key returned once — save it.',
        body: {
          name: 'string (required, max 100 chars)',
          scopes: 'string[] (optional) — "read" | "write" | "generate"',
          expiresAt: 'ISO date string (optional)',
        },
        response: { id: 'string', key: 'visant_sk_xxx (shown once)', keyPrefix: 'string', name: 'string', scopes: 'string[]', expiresAt: 'string|null' },
      },
      {
        method: 'GET',
        path: '/api/api-keys',
        description: 'List all API keys for the authenticated user.',
        response: { keys: [{ id: 'string', keyPrefix: 'string', name: 'string', scopes: 'string[]', lastUsed: 'string|null', createdAt: 'string', expiresAt: 'string|null', active: 'boolean' }] },
      },
      {
        method: 'DELETE',
        path: '/api/api-keys/:id',
        description: 'Revoke an API key (soft delete).',
        response: { message: 'API key revoked' },
      },
    ],
    usage: {
      header: 'Authorization: Bearer visant_sk_xxx',
      mcp_endpoint: '/api/mcp',
      note: 'API keys are used for MCP server access and programmatic REST API calls.',
    },
  }, 3600);
});

/**
 * GET /docs/search
 * Full-text search across API endpoints and MCP tools
 * Query: ?q=<term> (2–100 chars)
 */
router.get('/search', (req: Request, res: Response) => {
  try {
    const queryParam = (req.query.q as string) || '';

    if (!queryParam || queryParam.trim().length === 0) {
      sendCachedJSON(res, { results: [], query: '', message: 'Search query is required' });
      return;
    }

    const query = validateSearchQuery(queryParam).toLowerCase();
    const openAPISpec = getOpenAPISpec();
    const mcpSpec = getMCPSpec();
    const results: Array<{ type: string; title: string; description: string; url: string }> = [];

    for (const [path, methods] of Object.entries(openAPISpec.paths)) {
      for (const [method, details] of Object.entries(methods as Record<string, any>)) {
        if (!['get', 'post', 'put', 'delete', 'patch'].includes(method)) continue;
        if (
          path.toLowerCase().includes(query) ||
          details.summary?.toLowerCase().includes(query) ||
          details.description?.toLowerCase().includes(query)
        ) {
          results.push({
            type: 'endpoint',
            title: `${method.toUpperCase()} ${path}`,
            description: details.summary ?? '',
            url: `/api/docs/api#${(details.tags || [])[0] || 'api'}`,
          });
        }
      }
    }

    for (const tool of mcpSpec.tools) {
      if (tool.name.toLowerCase().includes(query) || tool.description.toLowerCase().includes(query)) {
        results.push({
          type: 'tool',
          title: tool.name,
          description: tool.description,
          url: '/api/docs/plugin/mcp',
        });
      }
    }

    sendCachedJSON(res, { results, query }, TTL_SEARCH);
  } catch (err) {
    handleDocsError(err, res);
  }
});

/**
 * GET /docs/export
 * Export OpenAPI or MCP spec as downloadable file
 * Query: ?format=openapi|mcp
 */
router.get('/export', (req: Request, res: Response) => {
  try {
    const format = (req.query.format as string) || 'openapi';

    if (!['openapi', 'mcp'].includes(format)) {
      throw new ValidationError('Invalid export format. Use: openapi, mcp', { format });
    }

    if (format === 'openapi') {
      const spec = getOpenAPISpec();
      setDocsHeaders(res, 3600);
      res.setHeader('Content-Type', 'application/json; charset=utf-8');
      res.setHeader('Content-Disposition', 'attachment; filename="openapi.json"');
      res.json(spec);
    } else {
      const spec = getMCPSpec();
      setDocsHeaders(res, 3600);
      res.setHeader('Content-Type', 'application/json; charset=utf-8');
      res.setHeader('Content-Disposition', 'attachment; filename="mcp-spec.json"');
      res.json(spec);
    }
  } catch (err) {
    handleDocsError(err, res);
  }
});

/**
 * GET /docs/api/components-usage
 * Component usage metrics — requires scripts/reports/component-usage.json
 * Generate with: node scripts/analyze-components.js --json
 */
router.get('/api/components-usage', (_req: Request, res: Response) => {
  const metricsPath = join(process.cwd(), 'scripts', 'reports', 'component-usage.json');

  fsAsync.readFile(metricsPath, 'utf-8')
    .then(data => {
      const metrics = JSON.parse(data);
      sendCachedJSON(res, {
        success: true,
        generatedAt: new Date().toISOString(),
        summary: metrics.metadata,
        distribution: metrics.categorized,
        components: (metrics.components || []).map((c: any) => ({
          name: c.name,
          path: c.path,
          imports: c.imports,
          category: c.category,
          usage: calcComponentUsage(c.imports),
        })),
        topComponents: (metrics.components || []).slice(0, 10),
        orphaned: (metrics.components || []).filter((c: any) => c.imports === 0),
      }, 3600);
    })
    .catch((err: Error) => {
      setDocsHeaders(res);
      res.status(404).json({
        error: 'Component metrics not available',
        suggestion: 'Run: node scripts/analyze-components.js --json',
        details: err.message,
      });
    });
});

/**
 * GET /docs/api/component/:name
 * Usage details for a specific component by name (case-insensitive)
 */
router.get('/api/component/:name', (req: Request, res: Response) => {
  const { name } = req.params;

  // Sanitize: alphanumeric + hyphens only
  if (!/^[a-zA-Z0-9-]+$/.test(name)) {
    setDocsHeaders(res);
    res.status(400).json({ error: 'Invalid component name' });
    return;
  }

  const metricsPath = join(process.cwd(), 'scripts', 'reports', 'component-usage.json');

  fsAsync.readFile(metricsPath, 'utf-8')
    .then(data => {
      const metrics = JSON.parse(data);
      const component = (metrics.components || []).find(
        (c: any) => c.name.toLowerCase() === name.toLowerCase()
      );

      if (!component) {
        setDocsHeaders(res);
        res.status(404).json({ error: `Component '${name}' not found` });
        return;
      }

      sendCachedJSON(res, {
        success: true,
        component: { ...component, usage: calcComponentUsage(component.imports) },
      }, 3600);
    })
    .catch((err: Error) => {
      setDocsHeaders(res);
      res.status(500).json({ error: 'Failed to read component metrics', details: err.message });
    });
});

export default router;
