import type { DesignType } from '../types';

/**
 * Get the prompt format instructions used by generateSmartPrompt
 * This ensures consistency between ChatNode and MockupMachinePage
 * 
 * @returns Formatted instructions string for system prompt
 */
export function getMockupPromptFormatInstructions(): string {
  return `Image Prompt Generation Format (CRITICAL - MUST MATCH MockupMachine FORMAT):
When creating **[ACTION:prompt]** suggestions, you MUST follow this EXACT format used by the MockupMachine system (geminiService.generateSmartPrompt):

STRUCTURE (MANDATORY ORDER):
1. Aspect Ratio Prefix (CRITICAL - MUST BE FIRST):
   - '16:9': "A photorealistic, super-detailed widescreen cinematic shot of..."
   - '4:3': "A photorealistic, super-detailed standard photo of..."
   - '1:1': "A photorealistic, super-detailed square composition of..."

2. Mockup Subject & Design Type:
   - Blank: "a blank white [category] mockup. The scene should be clean, minimalist, and ready for a design to be placed on it."
   - Logo: "a [category] mockup featuring the provided logo."
   - Layout: "a [category] mockup featuring the provided design."

3. Branding Style (if available from context):
   - "The brand's style is: [branding tags]."

4. Location/Setting (integrate naturally):
   - Minimalist Studio: "The scene should be set in a professional photography studio with infinite white wall background, studio lighting, clean and minimalist aesthetic. The scene should include a plant in the setting."
   - Light Box: "The scene should be set in a professional lightbox photography environment with seamless white or neutral background, even diffused lighting, completely neutral and minimal aesthetic. This is a professional product photography setup with no decorative elements, plants, or distractions - purely focused on showcasing the product with clean, professional lighting."
   - Other locations: "The scene should be set in or evoke the aesthetic of: [location tags]."

5. Camera Angle (if relevant):
   - "The camera angle should be: [angle tags]."

6. Lighting (integrate naturally):
   - "The lighting should be: [lighting tags]."

7. Visual Effects (if relevant):
   - "Apply a visual effect of: [effect tags]."

8. Materials & Textures (if relevant):
   - "The materials and textures should feature: [material tags]."

9. Color Palette (if available):
   - "The scene's color palette should be dominated by or feature accents of: [colors]. This should influence background, lighting, and environmental elements, not the uploaded design itself."

10. Realism Emphasis:
    - "Emphasize authentic materials, subtle surface details, and professional product photography lighting with sharp focus."

11. Design Integrity (if not blank):
    - "Place the design exactly as provided, without modification, cropping, or re-drawing."
    - For logos: "When placing the design, ensure a comfortable safe area or 'breathing room' around it. The design must never touch or be clipped by the edges of the mockup surface."

12. Text Generation:
    - Blank: "There should be absolutely no text, logos, or any other graphic elements on the mockup surfaces."
    - Non-blank: "No additional text, words, or letters should be generated. The design is the sole graphic element."

13. Negative Prompt (if provided):
    - "AVOID THE FOLLOWING: [negative prompt]."

FORMAT RULES:
- Write as ONE continuous paragraph (150-300 words)
- Use commas to separate elements within sections
- Be concise and objective - prioritize clarity over descriptive prose
- Only use concepts from available tags - don't introduce unrelated elements
- Integrate tags naturally into narrative, don't list them separately

This format MUST match exactly the format generated by generateSmartPrompt() in geminiService.ts.`;
}

/**
 * Build the instructions template for Gemini API (used in generateSmartPrompt)
 * This is the actual prompt sent to Gemini to generate prompts
 * 
 * @param params - Parameters for building the template
 * @returns Template string with placeholders for values
 */
export function buildGeminiPromptInstructionsTemplate(params: {
  designType: DesignType;
  isBlankMockup: boolean;
  withHuman: boolean;
  enhanceTexture: boolean;
  locationTags: string[];
}): string {
  const { designType, isBlankMockup, withHuman, enhanceTexture, locationTags } = params;

  const designTypeDescription = isBlankMockup
    ? 'A blank mockup (no design provided)'
    : `A standalone ${designType}`;

  const designTypeHandlingInstruction = isBlankMockup
    ? `3.  **Handle Design Type:** The user selected 'blank mockup'. The prompt should describe a clean, empty mockup ready for a design, with a white or neutral surface.`
    : `3.  **Handle Design Type:** If the type is 'logo', the prompt should focus on placing the logo onto the mockup surface. If the type is 'layout', the prompt should describe applying the entire graphic to the mockup surface (e.g., as a full book cover or poster design).`;

  const textGenerationInstruction = isBlankMockup
    ? `9.  **Text Generation:** The user wants a blank mockup. Explicitly state "Absolutely no text, letters, or words should be generated in the image."`
    : `9.  **Text Generation:** If "Generate Placeholder Text" is Yes, include a phrase like "with plausible placeholder text for realism". If No, state "The design should be the sole focus, with absolutely no additional text, words, or letters generated anywhere in the image. Avoid text or letters.".`;

  const humanInteractionInstruction = withHuman
    ? (isBlankMockup
      ? `10. **Human Interaction:** The user wants to include a human person in the scene. The scene should include a human person appearing in or interacting with the mockup in a natural, contextual way. The person should be shown in a way that makes sense for the mockup type and setting.`
      : `10. **Human Interaction:** The user wants to include a human person in the scene. The scene should include a human person appearing in or interacting with the mockup product in a natural, contextual way. The person should be shown using, holding, or interacting with the product in a way that makes sense for the mockup type.`)
    : '';

  const designIntegrityStepNumber = withHuman ? 11 : 10;
  const isLogo = designType === 'logo';
  const safeAreaInstruction = isLogo
    ? `\n${designIntegrityStepNumber + 1}. **Safe Area (CRITICAL):** The prompt must instruct the image generator to leave a comfortable 'safe area' or 'breathing room' around the uploaded design, stating that the design must not touch or be clipped by the edges of the mockup surface.`
    : '';

  const designIntegrityInstructions = isBlankMockup
    ? `${designIntegrityStepNumber}. **No Graphics:** The prompt must instruct the model to generate a completely blank mockup with no logos, text, or other graphic elements.`
    : `${designIntegrityStepNumber}. **Preserve the Design Integrity (CRITICAL):** The final prompt MUST include a clear instruction to use the uploaded design *exactly as provided*, forbidding any alteration, modification, or re-drawing. Use a sentence like: "It is crucial that the provided design is placed on the mockup surfaces exactly as it is, without any modification or re-drawing of the original design."${safeAreaInstruction}`;

  const locationInstruction = locationTags.includes('Minimalist Studio')
    ? `5.  **Minimalist Studio Setting (SPECIAL):** If "Minimalist Studio" is selected as the location, describe it as "a professional photography studio with infinite white wall background, studio lighting, clean and minimalist aesthetic". Include a plant in the setting.`
    : `5.  **Incorporate Additional Details:** If the user provides "Additional Details (MUST HAVE)", integrate these keywords and concepts naturally into the core description of the scene. These are high-priority requirements.`;

  return `You are an expert AI prompt engineer. Your task is to convert user selections into a concise and effective prompt for an AI image generator to create a photorealistic product mockup.

**USER'S INPUT:**
-   **Design Type:** ${designTypeDescription}
-   **Branding Style:** [BRANDING_TAGS]
-   **Mockup Subject(s):** [CATEGORY_TAGS]
-   **Color Palette:** [COLORS]
-   **Setting/Location:** [LOCATION_TAGS]
-   **Camera Angle:** [ANGLE_TAGS]
-   **Lighting Style:** [LIGHTING_TAGS]
-   **Visual Effects:** [EFFECT_TAGS]
-   **Generate Placeholder Text:** [GENERATE_TEXT]
-   **Include Human Interaction:** [WITH_HUMAN]
-   **Additional Details (MUST HAVE):** [ADDITIONAL_PROMPT]
-   **Aspect Ratio:** [ASPECT_RATIO]
-   **Negative Prompt (AVOID):** [NEGATIVE_PROMPT]


**INSTRUCTIONS:**
Based ${isBlankMockup ? '' : 'on the user\'s input and the provided design image, '}write an improved prompt.
1.  **Be Concise & Objective:** Combine the user's selections into a clear, direct, and effective prompt. Prioritize clarity and efficiency over descriptive prose.
2.  **Aspect Ratio is Paramount (CRITICAL):** Start the entire prompt with the aspect ratio description. This is the most important rule.
    - For '16:9', start with: "A photorealistic, super-detailed widescreen cinematic shot of..."
    - For '4:3', start with: "A photorealistic, super-detailed standard photo of..."
    - For '1:1', start with: "A photorealistic, super-detailed square composition of..."
${designTypeHandlingInstruction}
4.  **Focus on Realism:** After the aspect ratio prefix, describe the scene. Emphasize photorealistic details: ${enhanceTexture ? '"authentic materials", "subtle surface details", ' : ''}"natural reflections", "professional product photography", "sharp focus".
${locationInstruction}
6.  **Color Palette:** If the user specifies a color palette, integrate it into the prompt. For example: "The scene's color palette should be dominated by or feature accents of: [colors]." This should influence background, lighting, and environmental elements, not the uploaded design itself.
7.  **Structure:** The output must be a single, direct paragraph.
8.  **Strictly Adhere:** Only use concepts derived from the user's selections. Do not introduce new, unrelated elements.
${textGenerationInstruction}
${humanInteractionInstruction}
${designIntegrityInstructions}
${isBlankMockup ? (designIntegrityStepNumber + 1) : (designIntegrityStepNumber + 2)}. **Negative Prompt:** If the user has provided a negative prompt, end your response with a new sentence: "AVOID THE FOLLOWING: [negative prompt]."

**Your output must be ONLY the generated prompt text.**`;
}






