/// <reference types="@figma/plugin-typings" />

/**
 * Create a visual representation of the analysis result on the Figma canvas
 */
export async function createStickyPrompt(prompt: string, name: string) {
  try {
    const selection = figma.currentPage.selection;
    let targetX = figma.viewport.center.x;
    let targetY = figma.viewport.center.y;

    if (selection.length > 0) {
      const node = selection[0];
      targetX = node.x + node.width + 100;
      targetY = node.y;
    }

    // Create a "Design Note" frame
    const frame = figma.createFrame();
    frame.name = `✨ Analysis: ${name}`;
    
    // Setup background and style
    frame.fills = [{ type: 'SOLID', color: { r: 0.07, g: 0.07, b: 0.07 } }];
    frame.strokes = [{ type: 'SOLID', color: { r: 0.2, g: 0.2, b: 0.2 } }];
    frame.strokeWeight = 1;
    frame.cornerRadius = 12;
    frame.effects = [{
      type: 'DROP_SHADOW',
      color: { r: 0, g: 0, b: 0, a: 0.25 },
      offset: { x: 0, y: 4 },
      radius: 12,
      visible: true,
      blendMode: 'NORMAL'
    }];

    // Layout
    frame.layoutMode = 'VERTICAL';
    frame.primaryAxisSizingMode = 'AUTO';
    frame.counterAxisSizingMode = 'FIXED';
    frame.paddingLeft = 24;
    frame.paddingRight = 24;
    frame.paddingTop = 20;
    frame.paddingBottom = 24;
    frame.itemSpacing = 16;
    frame.resize(320, 100); // Height will auto-expand

    // Load fonts
    await Promise.all([
      figma.loadFontAsync({ family: 'Inter', style: 'Bold' }),
      figma.loadFontAsync({ family: 'Inter', style: 'Regular' }),
      figma.loadFontAsync({ family: 'Inter', style: 'Medium' })
    ]);

    // Header with Icon-like behavior
    const header = figma.createFrame();
    header.name = 'Header';
    header.layoutMode = 'HORIZONTAL';
    header.primaryAxisSizingMode = 'AUTO';
    header.counterAxisSizingMode = 'AUTO';
    header.itemSpacing = 8;
    header.fills = [];
    header.layoutAlign = 'STRETCH';

    const title = figma.createText();
    title.fontName = { family: 'Inter', style: 'Bold' };
    title.characters = name.toUpperCase();
    title.fontSize = 10;
    title.letterSpacing = { value: 5, unit: 'PERCENT' };
    title.fills = [{ type: 'SOLID', color: { r: 0.5, g: 0.5, b: 0.5 } }];
    header.appendChild(title);
    frame.appendChild(header);

    // Prompt content
    const text = figma.createText();
    text.fontName = { family: 'Inter', style: 'Regular' };
    text.characters = prompt;
    text.fontSize = 12;
    text.lineHeight = { value: 160, unit: 'PERCENT' };
    text.fills = [{ type: 'SOLID', color: { r: 0.9, g: 0.9, b: 0.9 } }];
    text.layoutAlign = 'STRETCH';
    frame.appendChild(text);

    // Footer / Metadata
    const footer = figma.createText();
    footer.fontName = { family: 'Inter', style: 'Medium' };
    footer.characters = 'Generated by Visant AI Engine';
    footer.fontSize = 9;
    footer.fills = [{ type: 'SOLID', color: { r: 0.3, g: 0.3, b: 0.3 } }];
    footer.layoutAlign = 'STRETCH';
    frame.appendChild(footer);

    // Position and finalize
    frame.x = targetX;
    frame.y = targetY;
    
    figma.currentPage.appendChild(frame);
    figma.currentPage.selection = [frame];
    figma.viewport.scrollAndZoomIntoView([frame]);

    return frame;
  } catch (err) {
    console.error('[devTools] createStickyPrompt failed:', err);
    return null;
  }
}

/**
 * Remaps solid colors in the selection to the brand palette.
 * Groups unique source colors and maps them to brand colors by luminance rank,
 * so every occurrence of the same color becomes the same brand color.
 */
export async function varySelectionColors(brandColors?: string[]) {
  const selection = figma.currentPage.selection;
  if (selection.length === 0) {
    figma.notify('Selecione algo para variar as cores ✨');
    return;
  }

  const hexToRgb = (hex: string): RGB | null => {
    const clean = hex.replace('#', '').trim();
    if (clean.length !== 6) return null;
    const r = parseInt(clean.substring(0, 2), 16) / 255;
    const g = parseInt(clean.substring(2, 4), 16) / 255;
    const b = parseInt(clean.substring(4, 6), 16) / 255;
    if ([r, g, b].some((v) => Number.isNaN(v))) return null;
    return { r, g, b };
  };

  const palette: RGB[] = (brandColors || [])
    .map(hexToRgb)
    .filter((c): c is RGB => c !== null);

  if (palette.length === 0) {
    figma.notify('Nenhuma cor da Brand Guideline disponível. Selecione cores na seção COLORS.');
    return;
  }

  // Pass 1 — collect unique source colors across the whole selection
  const sourceSet = new Map<string, RGB>();
  for (const node of selection) {
    collectSolidColors(node, sourceSet);
  }

  if (sourceSet.size === 0) {
    figma.notify('Nenhuma cor sólida encontrada na seleção.');
    return;
  }

  // Build source → brand mapping.
  // Strategy: sort both by luminance and map by rank so relative contrast
  // (dark↔light relationships between colors) is preserved — this keeps
  // accessibility intact when, e.g., light cards sit on a dark background.
  // To still produce fresh variations on repeated clicks, we pick randomly
  // from a small window around each ideal rank instead of the exact index.
  const sortedSources = Array.from(sourceSet.entries())
    .map(([key, rgb]) => ({ key, rgb, lum: getLuminance(rgb) }))
    .sort((a, b) => a.lum - b.lum);

  const sortedPalette = [...palette]
    .map((rgb) => ({ rgb, lum: getLuminance(rgb) }))
    .sort((a, b) => a.lum - b.lum);

  const colorMap = new Map<string, RGB>();
  const N = sortedSources.length;
  const P = sortedPalette.length;
  const WINDOW = 1; // ±1 rank of wiggle room for variation

  // Randomly flip the palette direction each run so variations can swap
  // between light and dark modes — the relative contrast between elements
  // is preserved either way (dark↔light or light↔dark), but absolute
  // luminance inverts, unlocking full light/dark mode variations.
  const invert = Math.random() < 0.5;

  sortedSources.forEach((src, i) => {
    const baseIdeal = N === 1 ? Math.floor(P / 2) : Math.round((i * (P - 1)) / (N - 1));
    const ideal = invert ? P - 1 - baseIdeal : baseIdeal;
    const lo = Math.max(0, ideal - WINDOW);
    const hi = Math.min(P - 1, ideal + WINDOW);

    // Candidate indices within the luminance window, excluding identity.
    const candidates: number[] = [];
    for (let j = lo; j <= hi; j++) {
      if (rgbKey(sortedPalette[j].rgb) !== src.key) candidates.push(j);
    }
    // Fall back to the whole window if identity was the only option.
    const pool = candidates.length > 0 ? candidates : [ideal];
    const pick = pool[Math.floor(Math.random() * pool.length)];
    colorMap.set(src.key, sortedPalette[pick].rgb);
  });

  // Pass 2 — apply the mapping consistently
  for (const node of selection) {
    await remapNodeColors(node, colorMap);
  }

  figma.notify(`${N} cor(es) remapeadas para ${P} cor(es) da brand 🎨`);
}

function rgbKey(c: RGB): string {
  const to255 = (v: number) => Math.round(v * 255);
  return `${to255(c.r)},${to255(c.g)},${to255(c.b)}`;
}

function collectSolidColors(node: SceneNode, out: Map<string, RGB>) {
  if ('fills' in node && Array.isArray(node.fills)) {
    for (const fill of node.fills) {
      if (fill.type === 'SOLID' && fill.visible !== false) {
        const k = rgbKey(fill.color);
        if (!out.has(k)) out.set(k, fill.color);
      }
    }
  }
  if ('strokes' in node && Array.isArray(node.strokes)) {
    for (const stroke of node.strokes) {
      if (stroke.type === 'SOLID' && stroke.visible !== false) {
        const k = rgbKey(stroke.color);
        if (!out.has(k)) out.set(k, stroke.color);
      }
    }
  }
  if ('children' in node) {
    for (const child of node.children) collectSolidColors(child, out);
  }
}

async function remapNodeColors(node: SceneNode, colorMap: Map<string, RGB>) {
  if ('fills' in node && Array.isArray(node.fills)) {
    const newFills = node.fills.map((fill) => {
      if (fill.type === 'SOLID') {
        const mapped = colorMap.get(rgbKey(fill.color));
        if (mapped) return { ...fill, color: mapped };
      }
      return fill;
    });
    node.fills = newFills;
  }

  if ('strokes' in node && Array.isArray(node.strokes)) {
    const newStrokes = node.strokes.map((stroke) => {
      if (stroke.type === 'SOLID') {
        const mapped = colorMap.get(rgbKey(stroke.color));
        if (mapped) return { ...stroke, color: mapped };
      }
      return stroke;
    });
    node.strokes = newStrokes;
  }

  if (node.type === 'TEXT') {
    await ensureTextContrast(node);
  }

  if ('children' in node) {
    for (const child of node.children) {
      await remapNodeColors(child, colorMap);
    }
  }
}

async function ensureTextContrast(textNode: TextNode) {
  // Find background color by looking up parents
  let bgNode: SceneNode | null = textNode.parent as SceneNode;
  let bgColor: RGB = { r: 1, g: 1, b: 1 }; // Default white

  while (bgNode) {
    if ('fills' in bgNode && Array.isArray(bgNode.fills)) {
      const solid = bgNode.fills.find(f => f.type === 'SOLID' && f.visible !== false) as SolidPaint;
      if (solid) {
        bgColor = solid.color;
        break;
      }
    }
    bgNode = bgNode.parent as SceneNode;
  }

  const textFills = textNode.fills as Paint[];
  const textFill = textFills.find(f => f.type === 'SOLID') as SolidPaint;
  if (!textFill) return;

  const bgLum = getLuminance(bgColor);
  const textLum = getLuminance(textFill.color);
  
  const contrast = getContrastRatio(bgLum, textLum);

  // If contrast is poor (< 4.5), adjust text color
  if (contrast < 4.5) {
    const isBgDark = bgLum < 0.5;
    const newTextColor = isBgDark ? { r: 0.98, g: 0.98, b: 0.98 } : { r: 0.02, g: 0.02, b: 0.02 };
    textNode.fills = [{ ...textFill, color: newTextColor }];
  }
}

// --- COLOR UTILS ---

function getLuminance(rgb: RGB): number {
  const a = [rgb.r, rgb.g, rgb.b].map((v) => {
    return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
  });
  return a[0] * 0.2126 + a[1] * 0.7152 + a[2] * 0.0722;
}

function getContrastRatio(lum1: number, lum2: number): number {
  const brightest = Math.max(lum1, lum2);
  const darkest = Math.min(lum1, lum2);
  return (brightest + 0.05) / (darkest + 0.05);
}

// --- SELECTION UTILS ---

/**
 * Transforms selected frames (that are inside another frame) into Slices.
 * Useful for asset export optimization where children of a main container
 * needs to be flattened into exportable slices at the same positions.
 */
export async function selectionToSlices() {
  const selection = figma.currentPage.selection;
  if (selection.length === 0) {
    figma.notify('Selecione um ou mais frames para converter em slices ✂️');
    return;
  }

  // Sort selection by position (X then Y) for consistency
  const sorted = [...selection].sort((a, b) => {
    if (Math.abs(a.y - b.y) < 10) return a.x - b.x;
    return a.y - b.y;
  });

  const createdSlices: SliceNode[] = [];

  for (const node of sorted) {
    if (('width' in node) && node.parent) {
      const parent = node.parent;
      const slice = figma.createSlice();
      
      // Add to parent FIRST (Figma requires parent to be set before checking/setting layoutPositioning)
      if ('appendChild' in parent) {
        parent.appendChild(slice);
      }

      // Check if parent is an Auto Layout frame
      if (parent.type === 'FRAME' && parent.layoutMode !== 'NONE') {
        if ('layoutPositioning' in slice) {
          (slice as any).layoutPositioning = 'ABSOLUTE';
        }
      }

      // Preserve your custom names (e.g. "01 / Capa")
      slice.name = node.name;
      
      // Now position it exactly over the source node
      slice.x = node.x;
      slice.y = node.y;
      slice.resize(node.width, node.height);
      
      // High Quality Instagram Settings (@2x PNG)
      slice.exportSettings = [{
        format: 'PNG',
        suffix: '',
        constraint: { type: 'SCALE', value: 2 },
        contentsOnly: false // Captures seamless background from parent
      }];

      createdSlices.push(slice);
    }
  }

  if (createdSlices.length > 0) {
    figma.currentPage.selection = createdSlices;
    figma.notify(`✨ ${createdSlices.length} Slices sobrepostos com sucesso!`);
  } else {
    figma.notify('⚠ Selecione os frames do carrossel.');
  }
}
