import type {
  BrandGuideline,
  BrandGuidelineColor,
  BrandGuidelineTypography,
  BrandGuidelineGradient,
  BrandGuidelineShadow,
  BrandGuidelineBorder,
  BrandGuidelineMotion,
  BrandGuidelineTokens,
} from '../types/brandGuideline'

// ─── Output Types ────────────────────────────────────────────

export interface CompiledCSS {
  format: 'css'
  content: string
  filename: string
}

export interface CompiledTailwind {
  format: 'tailwind'
  content: string
  filename: string
}

export interface CompiledReactTokens {
  format: 'react'
  content: string
  filename: string
}

export interface CompiledSCSSMap {
  format: 'scss'
  content: string
  filename: string
}

export type CompiledOutput = CompiledCSS | CompiledTailwind | CompiledReactTokens | CompiledSCSSMap

export type CompileFormat = 'css' | 'tailwind' | 'react' | 'scss' | 'all'

// ─── Helpers ─────────────────────────────────────────────────

function slugify(str: string | undefined | null): string {
  if (!str) return 'unnamed'
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  const match = hex.replace('#', '').match(/^([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i)
  if (!match) return null
  return { r: parseInt(match[1], 16), g: parseInt(match[2], 16), b: parseInt(match[3], 16) }
}

function buildShadowCSS(s: BrandGuidelineShadow): string {
  if (s.css) return s.css
  const inset = s.type === 'inner' ? 'inset ' : ''
  const rgba = `rgba(${hexToRgb(s.color)?.r ?? 0}, ${hexToRgb(s.color)?.g ?? 0}, ${hexToRgb(s.color)?.b ?? 0}, ${s.opacity})`
  return `${inset}${s.x}px ${s.y}px ${s.blur}px ${s.spread}px ${rgba}`
}

function buildGradientCSS(g: BrandGuidelineGradient): string {
  if (g.css) return g.css
  const stops = g.stops.map(s => `${s.color} ${s.position}%`).join(', ')
  return g.type === 'radial'
    ? `radial-gradient(circle, ${stops})`
    : `linear-gradient(${g.angle}deg, ${stops})`
}

// ─── CSS Variables Compiler ──────────────────────────────────

function compileCSS(bg: BrandGuideline): string {
  const lines: string[] = []
  const brandName = bg.identity?.name || 'Brand'

  lines.push(`/* ${brandName} — Design Tokens */`)
  lines.push(`/* Generated by Visant Labs */`)
  lines.push('')
  lines.push(':root {')

  // Colors
  if (bg.colors?.length) {
    lines.push('  /* Colors */')
    for (const c of bg.colors) {
      const key = slugify(c.role || c.name)
      lines.push(`  --color-${key}: ${c.hex};`)
      const rgb = hexToRgb(c.hex)
      if (rgb) lines.push(`  --color-${key}-rgb: ${rgb.r}, ${rgb.g}, ${rgb.b};`)
    }
    lines.push('')
  }

  // Typography
  if (bg.typography?.length) {
    lines.push('  /* Typography */')
    for (const t of bg.typography) {
      const key = slugify(t.role)
      lines.push(`  --font-${key}: '${t.family}', sans-serif;`)
      if (t.size) lines.push(`  --font-${key}-size: ${t.size}px;`)
      if (t.lineHeight) lines.push(`  --font-${key}-line-height: ${t.lineHeight};`)
      if (t.letterSpacing) lines.push(`  --font-${key}-letter-spacing: ${t.letterSpacing};`)
    }
    lines.push('')
  }

  // Spacing
  if (bg.tokens?.spacing) {
    lines.push('  /* Spacing */')
    for (const [key, val] of Object.entries(bg.tokens.spacing)) {
      lines.push(`  --space-${key}: ${val}px;`)
    }
    lines.push('')
  }

  // Border Radius
  if (bg.tokens?.radius) {
    lines.push('  /* Border Radius */')
    for (const [key, val] of Object.entries(bg.tokens.radius)) {
      lines.push(`  --radius-${key}: ${val}px;`)
    }
    lines.push('')
  }

  // Shadows
  if (bg.shadows?.length) {
    lines.push('  /* Shadows */')
    for (const s of bg.shadows) {
      const key = slugify(s.name)
      lines.push(`  --shadow-${key}: ${buildShadowCSS(s)};`)
    }
    lines.push('')
  }

  // Gradients
  if (bg.gradients?.length) {
    lines.push('  /* Gradients */')
    for (const g of bg.gradients) {
      const key = slugify(g.name)
      lines.push(`  --gradient-${key}: ${buildGradientCSS(g)};`)
    }
    lines.push('')
  }

  // Borders
  if (bg.borders?.length) {
    lines.push('  /* Borders */')
    for (const b of bg.borders) {
      const key = slugify(b.role || b.name)
      lines.push(`  --border-${key}: ${b.width}px ${b.style} ${b.color};`)
    }
    lines.push('')
  }

  // Motion
  if (bg.motion) {
    lines.push('  /* Motion */')
    if (bg.motion.easing) lines.push(`  --ease-default: ${bg.motion.easing};`)
    if (bg.motion.durations) {
      lines.push(`  --duration-fast: ${bg.motion.durations.fast}ms;`)
      lines.push(`  --duration-medium: ${bg.motion.durations.medium}ms;`)
      lines.push(`  --duration-slow: ${bg.motion.durations.slow}ms;`)
    }
    lines.push('')
  }

  // Color Themes
  if (bg.colorThemes?.length) {
    lines.push('  /* Color Themes */')
    for (const t of bg.colorThemes) {
      const key = slugify(t.name)
      lines.push(`  --theme-${key}-bg: ${t.bg};`)
      lines.push(`  --theme-${key}-text: ${t.text};`)
      lines.push(`  --theme-${key}-primary: ${t.primary};`)
      lines.push(`  --theme-${key}-accent: ${t.accent};`)
    }
    lines.push('')
  }

  lines.push('}')

  // Utility classes
  lines.push('')
  lines.push('/* Utility Classes */')

  if (bg.colors?.length) {
    for (const c of bg.colors) {
      const key = slugify(c.role || c.name)
      lines.push(`.bg-${key} { background-color: var(--color-${key}); }`)
      lines.push(`.text-${key} { color: var(--color-${key}); }`)
    }
  }

  if (bg.typography?.length) {
    lines.push('')
    for (const t of bg.typography) {
      const key = slugify(t.role)
      lines.push(`.font-${key} { font-family: var(--font-${key}); font-size: var(--font-${key}-size); line-height: var(--font-${key}-line-height); }`)
    }
  }

  return lines.join('\n')
}

// ─── Tailwind Config Compiler ────────────────────────────────

function compileTailwind(bg: BrandGuideline): string {
  const brandName = bg.identity?.name || 'Brand'

  const config: any = {
    colors: {},
    fontFamily: {},
    fontSize: {},
    spacing: {},
    borderRadius: {},
    boxShadow: {},
    transitionDuration: {},
    transitionTimingFunction: {},
  }

  if (bg.colors?.length) {
    for (const c of bg.colors) {
      const key = slugify(c.role || c.name)
      config.colors[key] = c.hex
    }
  }

  if (bg.typography?.length) {
    for (const t of bg.typography) {
      const key = slugify(t.role)
      config.fontFamily[key] = [`'${t.family}'`, 'sans-serif']
      if (t.size) {
        config.fontSize[key] = [`${t.size}px`, { lineHeight: t.lineHeight ? `${t.lineHeight}` : '1.5' }]
      }
    }
  }

  if (bg.tokens?.spacing) {
    for (const [key, val] of Object.entries(bg.tokens.spacing)) {
      config.spacing[key] = `${val}px`
    }
  }

  if (bg.tokens?.radius) {
    for (const [key, val] of Object.entries(bg.tokens.radius)) {
      config.borderRadius[key] = `${val}px`
    }
  }

  if (bg.shadows?.length) {
    for (const s of bg.shadows) {
      config.boxShadow[slugify(s.name)] = buildShadowCSS(s)
    }
  }

  if (bg.motion?.durations) {
    config.transitionDuration.fast = `${bg.motion.durations.fast}ms`
    config.transitionDuration.medium = `${bg.motion.durations.medium}ms`
    config.transitionDuration.slow = `${bg.motion.durations.slow}ms`
  }

  if (bg.motion?.easing) {
    config.transitionTimingFunction.brand = bg.motion.easing
  }

  // Color Themes as nested color groups
  if (bg.colorThemes?.length) {
    for (const t of bg.colorThemes) {
      const key = slugify(t.name)
      config.colors[`theme-${key}`] = { bg: t.bg, text: t.text, primary: t.primary, accent: t.accent }
    }
  }

  // Remove empty objects
  for (const key of Object.keys(config)) {
    if (Object.keys(config[key]).length === 0) delete config[key]
  }

  const lines: string[] = []
  lines.push(`// ${brandName} — Tailwind Theme Extension`)
  lines.push(`// Generated by Visant Labs`)
  lines.push(`// Usage: import into tailwind.config.ts → theme.extend`)
  lines.push('')
  lines.push(`export const brandTheme = ${JSON.stringify(config, null, 2)} as const`)
  lines.push('')
  lines.push(`// tailwind.config.ts usage:`)
  lines.push(`// import { brandTheme } from './brand-tokens'`)
  lines.push(`// export default { theme: { extend: brandTheme } }`)

  return lines.join('\n')
}

// ─── React Tokens Compiler ───────────────────────────────────

function compileReactTokens(bg: BrandGuideline): string {
  const brandName = bg.identity?.name || 'Brand'

  const lines: string[] = []
  lines.push(`// ${brandName} — React Design Tokens`)
  lines.push(`// Generated by Visant Labs`)
  lines.push('')

  // Colors
  if (bg.colors?.length) {
    lines.push('export const colors = {')
    for (const c of bg.colors) {
      const key = slugify(c.role || c.name).replace(/-([a-z])/g, (_, l) => l.toUpperCase())
      const rgb = hexToRgb(c.hex)
      lines.push(`  ${key}: { hex: '${c.hex}', rgb: '${rgb ? `${rgb.r}, ${rgb.g}, ${rgb.b}` : ''}', name: '${c.name}' },`)
    }
    lines.push('} as const')
    lines.push('')
  }

  // Typography
  if (bg.typography?.length) {
    lines.push('export const typography = {')
    for (const t of bg.typography) {
      const key = slugify(t.role).replace(/-([a-z])/g, (_, l) => l.toUpperCase())
      lines.push(`  ${key}: { family: '${t.family}', size: ${t.size ?? 'undefined'}, lineHeight: ${t.lineHeight ?? 'undefined'}, weight: '${t.style ?? 'Regular'}' },`)
    }
    lines.push('} as const')
    lines.push('')
  }

  // Spacing
  if (bg.tokens?.spacing) {
    lines.push(`export const spacing = ${JSON.stringify(bg.tokens.spacing, null, 2)} as const`)
    lines.push('')
  }

  // Radius
  if (bg.tokens?.radius) {
    lines.push(`export const radius = ${JSON.stringify(bg.tokens.radius, null, 2)} as const`)
    lines.push('')
  }

  // Shadows
  if (bg.shadows?.length) {
    lines.push('export const shadows = {')
    for (const s of bg.shadows) {
      const key = slugify(s.name).replace(/-([a-z])/g, (_, l) => l.toUpperCase())
      lines.push(`  ${key}: '${buildShadowCSS(s)}',`)
    }
    lines.push('} as const')
    lines.push('')
  }

  // Gradients
  if (bg.gradients?.length) {
    lines.push('export const gradients = {')
    for (const g of bg.gradients) {
      const key = slugify(g.name).replace(/-([a-z])/g, (_, l) => l.toUpperCase())
      lines.push(`  ${key}: '${buildGradientCSS(g)}',`)
    }
    lines.push('} as const')
    lines.push('')
  }

  // Motion
  if (bg.motion) {
    const motion: any = {}
    if (bg.motion.easing) motion.easing = bg.motion.easing
    if (bg.motion.durations) motion.durations = bg.motion.durations
    if (bg.motion.philosophy) motion.philosophy = bg.motion.philosophy
    lines.push(`export const motion = ${JSON.stringify(motion, null, 2)} as const`)
    lines.push('')
  }

  // Color Themes
  if (bg.colorThemes?.length) {
    lines.push('export const colorThemes = {')
    for (const t of bg.colorThemes) {
      const key = slugify(t.name).replace(/-([a-z])/g, (_: string, l: string) => l.toUpperCase())
      lines.push(`  ${key}: { bg: '${t.bg}', text: '${t.text}', primary: '${t.primary}', accent: '${t.accent}' },`)
    }
    lines.push('} as const')
    lines.push('')
  }

  // Unified token object
  lines.push('export const tokens = {')
  if (bg.colors?.length) lines.push('  colors,')
  if (bg.typography?.length) lines.push('  typography,')
  if (bg.tokens?.spacing) lines.push('  spacing,')
  if (bg.tokens?.radius) lines.push('  radius,')
  if (bg.shadows?.length) lines.push('  shadows,')
  if (bg.gradients?.length) lines.push('  gradients,')
  if (bg.motion) lines.push('  motion,')
  if (bg.colorThemes?.length) lines.push('  colorThemes,')
  lines.push('} as const')
  lines.push('')
  lines.push('export type BrandTokens = typeof tokens')

  return lines.join('\n')
}

// ─── SCSS Map Compiler ───────────────────────────────────────

function compileSCSS(bg: BrandGuideline): string {
  const brandName = bg.identity?.name || 'Brand'
  const lines: string[] = []

  lines.push(`// ${brandName} — SCSS Design Tokens`)
  lines.push(`// Generated by Visant Labs`)
  lines.push('')

  if (bg.colors?.length) {
    lines.push('$brand-colors: (')
    for (const c of bg.colors) {
      lines.push(`  '${slugify(c.role || c.name)}': ${c.hex},`)
    }
    lines.push(');')
    lines.push('')
    for (const c of bg.colors) {
      lines.push(`$color-${slugify(c.role || c.name)}: ${c.hex};`)
    }
    lines.push('')
  }

  if (bg.typography?.length) {
    lines.push('$brand-fonts: (')
    for (const t of bg.typography) {
      lines.push(`  '${slugify(t.role)}': ('${t.family}', sans-serif),`)
    }
    lines.push(');')
    lines.push('')
  }

  if (bg.tokens?.spacing) {
    lines.push('$brand-spacing: (')
    for (const [key, val] of Object.entries(bg.tokens.spacing)) {
      lines.push(`  '${key}': ${val}px,`)
    }
    lines.push(');')
    lines.push('')
  }

  if (bg.tokens?.radius) {
    lines.push('$brand-radius: (')
    for (const [key, val] of Object.entries(bg.tokens.radius)) {
      lines.push(`  '${key}': ${val}px,`)
    }
    lines.push(');')
    lines.push('')
  }

  if (bg.shadows?.length) {
    lines.push('$brand-shadows: (')
    for (const s of bg.shadows) {
      lines.push(`  '${slugify(s.name)}': ${buildShadowCSS(s)},`)
    }
    lines.push(');')
    lines.push('')
  }

  if (bg.colorThemes?.length) {
    for (const t of bg.colorThemes) {
      const slug = slugify(t.name)
      lines.push(`$theme-${slug}-bg: ${t.bg};`)
      lines.push(`$theme-${slug}-text: ${t.text};`)
      lines.push(`$theme-${slug}-primary: ${t.primary};`)
      lines.push(`$theme-${slug}-accent: ${t.accent};`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

// ─── Public API ──────────────────────────────────────────────

export function compileBrandTokens(bg: BrandGuideline, format: CompileFormat): CompiledOutput[] {
  const brandSlug = slugify(bg.identity?.name || 'brand')

  const compilers: Record<Exclude<CompileFormat, 'all'>, () => CompiledOutput> = {
    css: () => ({ format: 'css', content: compileCSS(bg), filename: `${brandSlug}-tokens.css` }),
    tailwind: () => ({ format: 'tailwind', content: compileTailwind(bg), filename: `${brandSlug}-tailwind.ts` }),
    react: () => ({ format: 'react', content: compileReactTokens(bg), filename: `${brandSlug}-tokens.ts` }),
    scss: () => ({ format: 'scss', content: compileSCSS(bg), filename: `${brandSlug}-tokens.scss` }),
  }

  if (format === 'all') {
    return Object.values(compilers).map(fn => fn())
  }

  return [compilers[format]()]
}
